return {
    'romus204/tree-sitter-manager.nvim',
    enabled = true,
    event = { 'BufReadPre', 'BufNewFile' },
    dependencies = {},
    config = function()
        require('tree-sitter-manager').setup({
            ensure_installed = {
                'bash',
                'bibtex',
                'comment',
                'cpp',
                'css',
                'csv',
                'diff',
                'ecma',
                'dockerfile',
                'dtd',
                'editorconfig',
                'git_config',
                'gitcommit',
                'gitignore',
                'html',
                'html_tags',
                'http',
                'java',
                'javadoc',
                'javascript',
                'jq',
                'jsdoc',
                'json',
                'json5',
                'jsx',
                'latex',
                'lua',
                'luadoc',
                'make',
                'markdown',
                'markdown_inline',
                'mermaid',
                'python',
                'query',
                'regex',
                'rust',
                'scss',
                'sql',
                'ssh_config',
                'toml',
                'tsv',
                'typescript',
                'typst',
                'vim',
                'vimdoc',
                'vue',
                'xml',
                'yaml',
                'zsh',
            },
            border = 'single',
        })
    end,
}
